### PR TITLE
Fix of a bug with the kvInitPlugin

### PR DESCRIPTION
**Pull request by perlexed**
There is an error when we try to use Yii2 plugin DatePicker (which extends \kartik\date\DatePicker). The script tries to call jQuery's function this way:
$body.on('load', selector, callback());
but the 'callback' function returns no value.

### CODE REVIEW

**Comment by kartik-v** [comment]
What is the error you are facing? There is a specific reason for initializing the plugin via `body` selector to ensure that the plugin stays initialized even if the base input is overwritten by ajax.

**Comment by perlexed** [comment]
This is the code that is generated by the widget:

jQuery(document).ready(function () {
jQuery.fn.kvDatepicker.dates={};
kvInitPlugin(jQuery('#userinfo-birthday-kvdate').kvSelector(), function(){
  if (jQuery('#userinfo-birthday').data('kvDatepicker')) {
jQuery('#userinfo-birthday').kvDatepicker('destroy'); }
  jQuery('#userinfo-birthday-kvdate').kvDatepicker(kvDatepicker_8d73414f);
});
...

When it's executed, the kvInitPlugin function receives 2 parameters -
selector sting and the callback function (which doesn't return anything).
And in the kvInitPlugin function this part of the code

$body.on('load', selector, callback());

passes the result of the callback function to the .on() function, not the
callback function itself. And then 'add' jQuery function, which is called
by 'on', can't process further because 'data' parameter in the 'on'
function is null (as this is the result of the callback()).

2016-08-18 18:50 GMT+07:00 Kartik Visweswaran <notifications@github.com>:

**Comment by kartik-v** [comment]
I see. the callback is called incorrectly in body on load... but the event delegation is not working due to some reason because the load is called within document ready. Needs some study... till that time a plain callback execution on document ready.

**Comment by kartik-v** [comment]
Will be resolved via #71.

**Pull request closed without merging**
