### PR TITLE
Set the plugins used in the input.

### PR DESCRIPTION
**Pull request by thiagotalma**
Thus we can write scripts that clone an input and implement all the plugins in the new input.

### CODE REVIEW

**Comment by thiagotalma** [comment]
@kartik-v Please take a look at it.

**Comment by kartik-v** [comment]
You could currently get it this way isn't it?

```js
function getKrajeePlugins() {
    var plugins = [], key = 0;
    $('#input').data().each(function(i, attr) {
         if (attr.substring(0, 6) === 'krajee') {
                plugins[key] = attr;
                key++;
        }
    });
    return plugins;
}
```

**Comment by thiagotalma** [comment]
Yes, I could.

But you're not the only one who creates plugins.
If there is no standard, soon we will have solutions like this:

```javascript
function getWhateverPlugins() {
    var plugins = [], key = 0;
    $('#input').data().each(function(attr, val) {
         if (
                attr.substring(0, 6) === 'krajee'
                || attr.substring(0, 6) === 'talma'
                || attr.substring(0, 6) === 'john'
                || attr.substring(0, 6) === 'doe'
                || attr.substring(0, 6) === 'mike'
                || attr.substring(0, 6) === 'jack'
                || attr.substring(0, 6) === 'thompson'
                || attr.substring(0, 6) === 'ted'
                || attr.substring(0, 6) === 'james'
                || attr.substring(0, 6) === 'cebe'
            ) {
                plugins[key] = attr;
                key++;
        }
    });
    return plugins;
}
```
Would not it be wiser to standardize?

Hugs!

**Comment by kartik-v** [comment]
Not clear.

I have already standardized an approach for all of the Krajee extensions and jquery plugins used. 

But there is no consistent standard on this for other third party extensions. Currently no third party extension maintains data attributes that contain plugin settings  necessarily like krajee. So you cannot have this anyway as an universal solution for other vendor's extensions. Nor can that be fixed in this yii2-krajee code base.

But your example on the contrary assumes some standardization. I would say then it becomes easy. If everyone where to use the same concept as krajee. You can do this and just maintain a vendors array containing all the vendors 

```js
// just maintain vendors
var vendors = ['krajee', 'vendor1', 'vendor2'];

function getVendorPlugins() {
    var plugins = [], i, key = 0;
    for (i = 0; i < vendors.length; i++) {
        $('#input').data().each(function(attr, val) {
            if (attr.substring(0, 6) === vendors[i]) {
                plugins[key] = attr;
                key++;
            }
        });
    }
    return plugins;
}
```

**Comment by thiagotalma** [comment]
Okay. You're the boss, man!

**Comment by kartik-v** [comment]
Refer #40 for auto plugin initialization via pjax.

**Pull request closed without merging**
